"""Shared Pydantic schemas for the Workforce Intelligence platform.

These models mirror the SQL DDL and serve as the canonical wire format
between every service. Importing from `wfi_schemas` should never trigger
any I/O — pure types only.
"""

from wfi_schemas.audit import ActionType, AuditLogEntry
from wfi_schemas.candidate import (
    AvailabilityWindow,
    Candidate,
    CandidateSource,
    CandidateStatus,
    CareerArc,
    CareerHistoryEntry,
    Citizenship,
    ClearanceStatus,
    ClearanceType,
    CompensationEntry,
    CompTrajectory,
    EngagementSignals,
    PolygraphType,
    PreferredChannel,
    SalesMotion,
    SeOrientation,
)
from wfi_schemas.events import (
    AgentType,
    Channel,
    EventType,
    InteractionEvent,
    Outcome,
)
from wfi_schemas.govcon import (
    AdjudicationStatus,
    Agency,
    AlertChannel,
    AlertHistory,
    AlertRule,
    AlertSeverity,
    AlertStatus,
    AlertTriggerType,
    Assignment,
    AssignmentStatus,
    BaseOrOption,
    Certification,
    CertificationStatus,
    Clearance,
    Contract,
    ContractCreate,
    ContractSource,
    ContractStatus,
    ContractUpdate,
    EducationLevel,
    Employee,
    EmployeeCreate,
    EmployeeStatus,
    EmployeeUpdate,
    GapAnalysis,
    GapRiskLevel,
    Lcat,
    LcatRequirement,
    RecompeteEvent,
    RecompeteEventType,
    RecompeteRisk,
    SetAsideType,
    Vendor,
)
from wfi_schemas.govcon import (
    ClearanceLevel as GovConClearanceLevel,
)
from wfi_schemas.govcon import (
    PolyType as GovConPolyType,
)
from wfi_schemas.requisition import (
    CompType,
    EmployerRubric,
    ReqConvictionTier,
    ReqExclusivity,
    ReqStatus,
    ReqType,
    Requisition,
    ReqUrgency,
)
from wfi_schemas.scorecard import (
    DimensionScore,
    EscalationFlag,
    Recommendation,
    Scorecard,
)

__all__ = [
    "ActionType",
    "AdjudicationStatus",
    "Agency",
    "AgentType",
    "AlertChannel",
    "AlertHistory",
    "AlertRule",
    "AlertSeverity",
    "AlertStatus",
    "AlertTriggerType",
    "Assignment",
    "AssignmentStatus",
    "AuditLogEntry",
    "AvailabilityWindow",
    "BaseOrOption",
    "Candidate",
    "CandidateSource",
    "CandidateStatus",
    "CareerArc",
    "CareerHistoryEntry",
    "Certification",
    "CertificationStatus",
    "Channel",
    "Citizenship",
    "Clearance",
    "ClearanceStatus",
    "ClearanceType",
    "CompTrajectory",
    "CompType",
    "CompensationEntry",
    "Contract",
    "ContractCreate",
    "ContractSource",
    "ContractStatus",
    "ContractUpdate",
    "DimensionScore",
    "EducationLevel",
    "Employee",
    "EmployeeCreate",
    "EmployeeStatus",
    "EmployeeUpdate",
    "EmployerRubric",
    "EngagementSignals",
    "EscalationFlag",
    "EventType",
    "GapAnalysis",
    "GapRiskLevel",
    "GovConClearanceLevel",
    "GovConPolyType",
    "InteractionEvent",
    "Lcat",
    "LcatRequirement",
    "Outcome",
    "PolygraphType",
    "PreferredChannel",
    "Recommendation",
    "RecompeteEvent",
    "RecompeteEventType",
    "RecompeteRisk",
    "ReqConvictionTier",
    "ReqExclusivity",
    "ReqStatus",
    "ReqType",
    "ReqUrgency",
    "Requisition",
    "SalesMotion",
    "Scorecard",
    "SeOrientation",
    "SetAsideType",
    "Vendor",
]
