"""Client submission package generator.

Produces the formatted candidate presentation pack the AE / hiring
manager sees. Markdown by default; HTML for portals. Pulls scorecard
highlights, evidence quotes, and risk flags into a tight one-pager.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from wfi_schemas import Candidate, Requisition, Scorecard


@dataclass
class SubmissionPackage:
    candidate_id: str
    requisition_id: str
    headline: str
    summary_md: str
    detail_md: str
    risk_flags: list[str]
    recommendation: str
    pass_ratio: float


def generate(candidate: Candidate, requisition: Requisition, scorecard: Scorecard) -> SubmissionPackage:
    headline = f"{candidate.first_name} {candidate.last_name} — {requisition.title}"
    summary = _summary(candidate, requisition, scorecard)
    detail = _detail(candidate, requisition, scorecard)
    return SubmissionPackage(
        candidate_id=str(candidate.id),
        requisition_id=str(requisition.id),
        headline=headline,
        summary_md=summary,
        detail_md=detail,
        risk_flags=list(scorecard.risk_flags),
        recommendation=scorecard.recommendation,
        pass_ratio=scorecard.pass_ratio,
    )


def _summary(c: Candidate, r: Requisition, s: Scorecard) -> str:
    location = f"{c.location_metro}, {c.location_state}" if c.location_metro else "(location not provided)"
    clearance = c.clearance_type.upper().replace("_", " ") if c.clearance_type != "none" else "no clearance"
    return (
        f"**{c.first_name} {c.last_name}** — {location}\n\n"
        f"- Recommendation: **{s.recommendation.upper()}** (pass ratio {s.pass_ratio * 100:.0f}%)\n"
        f"- Motion: {c.primary_motion or 'unspecified'}\n"
        f"- Clearance: {clearance}\n"
        f"- Most recent role: {(c.career_history[0].title if c.career_history else 'n/a')}\n"
        f"- Summary: {s.summary or '_no narrative available_'}\n"
    )


def _detail(c: Candidate, r: Requisition, s: Scorecard) -> str:
    parts: list[str] = []
    parts.append("## Why this candidate")
    parts.append(s.summary or "_(no LLM summary)_")
    parts.append("\n## Career history")
    for entry in c.career_history[:5]:
        parts.append(
            f"- **{entry.title}** at {entry.company} "
            f"({entry.start_date or '?'} – {entry.end_date or 'present'})"
        )
    parts.append("\n## Rubric scorecard")
    for crit in s.criterion_results:
        check = "✓" if crit.get("passed") else "✗"
        parts.append(f"- {check} **{crit.get('key')}** — {crit.get('description', '')}")
    if s.dimensional_scores:
        parts.append("\n## Dimensional scores")
        for d in s.dimensional_scores:
            parts.append(f"- **{d.dimension}** — {d.score:.1f}/5 — {d.reasoning}")
            for q in d.evidence_quotes[:2]:
                parts.append(f"   > \"{q}\"")
    if s.risk_flags:
        parts.append("\n## Risks")
        for flag in s.risk_flags:
            parts.append(f"- {flag}")
    parts.append("\n_Generated by the Workforce Intelligence Platform — every assessment is auditable in the platform._")
    return "\n".join(parts)


def to_dict(pkg: SubmissionPackage) -> dict[str, Any]:
    return {
        "candidate_id": pkg.candidate_id,
        "requisition_id": pkg.requisition_id,
        "headline": pkg.headline,
        "summary_md": pkg.summary_md,
        "detail_md": pkg.detail_md,
        "risk_flags": pkg.risk_flags,
        "recommendation": pkg.recommendation,
        "pass_ratio": pkg.pass_ratio,
    }
